name: Repo syncer
on:
  schedule:
    - cron: "0 */6 * * *"
jobs:
  sync_plz_thx:
    name: Sync and push
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: '0'        # fetch all history
        token: ${{ secrets.PAT }}
    - name: ./actions/syncer/
      uses: ./actions/syncer/
    - name: The job has failed
      if: ${{ failure() }}
      uses: JasonEtco/create-an-issue@v2
      env:
        GITHUB_TOKEN: ${{ secrets.PAT }}
      with:
        filename: .github/sync-failed-template.md
        update_existing: true
